version: '2'
services:
  discovery:
    image: zookeeper:3.4
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  ui:
    build: ui
    ports:
      - 80:8080
    links:
      - discovery
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  passenger:
    build: passenger
    links:
      - passenger-database
    environment:
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  passenger-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - passenger-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: passenger
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  trip:
    build: trip
    links:
      - trip-database
      - discovery
    environment:
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  trip-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - trip-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: trip
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification:
    build: notification
    links:
      - notification-database
    environment:
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - notification-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: notification
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  driver:
    build: driver
    links:
      - driver-database
    environment:
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  driver-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - driver-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: driver
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  billing:
    build: billing
    links:
      - billing-database
    environment:
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASS: $DATABASE_PASS
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  billing-database:
    image: mariadb:10
    expose:
      - 3306
    volumes:
      - billing-data:/var/lib/mysql
    environment:
      MYSQL_USER: $DATABASE_USER
      MYSQL_ROOT_PASSWORD: $DATABASE_PASS
      MYSQL_DATABASE: billing
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  passenger-data:
  trip-data:
  notification-data:
  driver-data:
  billing-data: